<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 static/assets/models/keychains/bubba.glb
-->

<script lang="ts">
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	export let assetURL: string;

	export const ref = new Group();

	const gltf = useGltf(assetURL, { useDraco: true });

	const component = forwardEventHandlers();

	// $: gltf.then((x) => console.log(x.nodes));

	function assetURLtoNodeName(assetURL: string): string {
		let assetName = assetURL.split('/').pop()?.split('.').shift() ?? '';
		let assetNameCap = assetName.charAt(0).toUpperCase() + assetName.slice(1);
		// console.log('Asset name cap:', assetNameCap);
		switch (assetNameCap) {
			case 'Jimmy':
				return 'Chimkin';
			case 'Bloom_and_gloom':
				return 'bloom_and_gloom';
			case 'Death_sensei':
				return 'Death_Sensei';
			case 'Fluffians':
				return 'fluffians';
			case 'Mr_squeaks':
				return 'Mr_Squeaks';
			case 'Pebble':
				return 'Pebbles';
			case 'Tako':
				return 'tako';
			default:
				return assetNameCap;
		}
	}
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh geometry={gltf.nodes[assetURLtoNodeName(assetURL)].geometry} castShadow>
			<T.MeshStandardMaterial color="#ffffff"></T.MeshStandardMaterial>
		</T.Mesh>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
