<script lang="ts">
	import FanboothDemoImg from '$lib/assets/fanbooth-demo.png';
</script>

<svelte:head>
	<title>Hololive Fan Booth - About</title>
	<meta
		name="description"
		content="Info about the Hololive Dokomi 2025 fan booth, such as who organizes it, where it is from, what are VTubers etc." />
</svelte:head>

<div class="bg-triangles bg-primary bg-fixed">
	<div class="hero h-[screen]">
		<div class="hero-content mx-8 flex-col font-geologica lg:flex-row-reverse">
			<img
				width="800"
				height="1000"
				src={FanboothDemoImg}
				class="max-w-xs"
				alt="Fan Booth Illustration by Pungson Mori" />
			<div>
				<h1 class="text-8xl font-bold tracking-tighter text-secondary">About the Fan Booth</h1>
				<p class="py-6 text-2xl font-semibold text-base-100">
					The unofficial Fan Booth is a project organised for the third year in a row at <a
						href="https://www.dokomi.de/en"
						class="link-secondary link transition-colors">DoKomi</a
					>, Germany's biggest Anime and Japan Expo.
				</p>
			</div>
		</div>
	</div>

	<div class="hero bg-secondary sm:h-[40vh]">
		<div class="hero-content flex-col lg:flex-row-reverse">
			<div class="mx-8 space-y-4 font-geologica">
				<h1 class="text-center text-6xl font-bold tracking-tight text-primary">
					What are VTubers?
				</h1>
				<p class="py-6 text-2xl font-semibold text-base-100">
					<a
						href="https://virtualyoutuber.fandom.com/wiki/VTuber"
						class="link font-bold text-primary">VTubers</a
					>, or virtual YouTubers, are online entertainers who use digital avatars generated by
					computer graphics. They deliver content on platforms such as YouTube or Twitch, with their
					avatars often resembling anime-style characters.
				</p>
			</div>
		</div>
	</div>

	<div class="hero bg-transparent sm:h-[40vh]">
		<div class="hero-content flex-col lg:flex-row-reverse">
			<div class="mx-8 space-y-4 font-geologica">
				<h1 class="text-center text-6xl font-bold tracking-tight text-base-100">
					What is <span class="text-secondary underline">hololive</span>?
				</h1>
				<p class="py-6 text-2xl font-semibold text-base-100">
					<a href="https://hololivepro.com/en/" class="link-secondary link transition-colors"
						>Hololive Production</a>
					is a VTuber agency consisting of hololive and HOLOSTARS. Owned by the Japanese company
					<a href="https://cover-corp.com" class="link-secondary link transition-colors"
						>Cover Corporation</a
					>, Hololive's VTubers deliver regular livestreams on platforms like YouTube and Twitch,
					where they engage in activities ranging from singing to playing video games.
				</p>
			</div>
		</div>
	</div>
</div>
