<script lang="ts">
	import type { PageData } from './$types';

	export let data: PageData;
</script>

<div class="p-10 bg-stars bg-fixed">
	<div class="max-w-4xl mx-auto">
		<section class="mb-10 space-y-8">
			<h1 class="text-4xl mb-4 font-bold text-secondary">What are VTubers?</h1>
			<!-- svelte-ignore a11y-img-redundant-alt -->
			<img
				class="mask mask-squircle"
				src="https://static.wikia.nocookie.net/virtualyoutuber/images/f/f5/Kizunaai.jpg"
				alt="Image of Kizuna Ai"
			/>
			<p class="text-lg">
				<a href="https://virtualyoutuber.fandom.com/wiki/VTuber" class="link link-primary"
					>VTubers</a
				>, or virtual YouTubers, are online entertainers who use digital avatars generated by
				computer graphics. They deliver content on platforms such as YouTube or Twitch, with their
				avatars often resembling anime-style characters.
			</p>
		</section>

		<section class="mb-10 space-y-8">
			<h1 class="text-4xl mb-4 font-bold text-secondary">What is Hololive?</h1>
			<img
				class="max-w-sm"
				src="https://upload.wikimedia.org/wikipedia/commons/d/df/Hololive_Production_logo.svg"
				alt="Hololive Production Logo"
			/>
			<p class="text-lg">
				<a href="https://hololivepro.com/en/" class="link link-primary">Hololive Production</a> is a
				VTuber agency consisting of hololive and HOLOSTARS. Owned by the Japanese company
				<a href="https://cover-corp.com" class="link link-primary">Cover Corporation</a>, Hololive's
				VTubers deliver regular livestreams on platforms like YouTube and Twitch, where they engage
				in activities ranging from singing to playing video games.
			</p>
		</section>

		<section class="mb-10">
			<h1 class="text-4xl mb-4 font-bold text-secondary">About DoKomi</h1>
			<p class="text-lg">
				<a href="https://www.dokomi.de/en" class="link link-primary">DoKomi</a> is the largest anime
				and Japan expo in Germany. It's a yearly event where fans of anime, manga, and Japanese culture
				can gather to celebrate their passions, meet artists, participate in workshops, and even meet
				some of their favorite VTubers.
			</p>
		</section>
	</div>
</div>

<style>
	.bg-stars {
		background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24'%3E%3Cg fill='%23546aff' fill-opacity='0.1'%3E%3Cpolygon fill-rule='evenodd' points='8 4 12 6 8 8 6 12 4 8 0 6 4 4 6 0 8 4'/%3E%3C/g%3E%3C/svg%3E");
	}
</style>
